name: CI

on: pull_request

jobs:
  test:
    name: Test
    runs-on: [ self-hosted, jimdo-runner-1core ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test the application
        run: make test

      - name: Build the application
        run: make build